### ISSUE TITLE
Matomo v5

### ISSUE THREAD

**Issue by Beltshassar** [Starker3/MatomoiPadDetector#1]
Hi

Thanks for you great Matomo plugin.

Do you have any plans on Matomo v.5 compatability?

Best regards

Daniel

**Comment by Starker3** [comment]
Hi @Beltshassar 
Thanks for using the plugin!

There is already a Matomo v5 compatible version of the plugin available on the Matomo marketplace: https://plugins.matomo.org/iPadDetector

If you're having issues downloading or installing it in Matomo 5, please let me know.
